"""Core algorithms for semantic caching."""

from .chunking import (
    get_optimal_chunker,
    hypercdc_chunks,
    hypercdc_simd_boundaries,
    hypercdc_simd_chunks,
)
from .compression import compress_adaptive, decompress, estimate_entropy
from .embeddings import embed, embed_query, get_model_info
from .embeddings import warmup as warmup_embeddings
from .hashing import (
    DeduplicateIndex,
    HierarchicalHasher,
    StreamingHasher,
    get_hash_stats,
    hash_chunk,
    hash_chunk_binary,
    hash_content,
)
from .similarity import (
    DEFAULT_LSH_CONFIG,
    LSHConfig,
    LSHIndex,
    batch_dot_product_ternary,
    batch_hamming_similarity_binary,
    compute_simhash,
    cosine_similarity,
    cosine_similarity_batch,
    cosine_similarity_batch_matrix,
    create_lsh_index,
    dequantize_binary,
    dequantize_embedding,
    dequantize_ternary,
    evaluate_quantization_accuracy,
    hamming_distance,
    hamming_similarity_binary,
    quantize_binary,
    quantize_embedding,
    quantize_hybrid,
    quantize_ternary,
    similarity_from_quantized_blob,
    top_k_from_quantized,
    top_k_similarities,
)
from .text import (
    DEFAULT_SUMMARIZATION_CONFIG,
    DiffDelta,
    Segment,
    SummarizationConfig,
    apply_delta,
    compute_delta,
    diff_stats,
    extract_segments,
    generate_diff,
    score_segments,
    summarize_semantic,
    truncate_semantic,
    truncate_smart,
    truncate_with_summarization,
)
from .tokenizer import BPETokenizer, count_tokens, get_tokenizer

__all__ = [
    "hypercdc_chunks",
    "hypercdc_simd_chunks",
    "hypercdc_simd_boundaries",
    "get_optimal_chunker",
    "LSHConfig",
    "LSHIndex",
    "compute_simhash",
    "create_lsh_index",
    "hamming_distance",
    "DEFAULT_LSH_CONFIG",
    "compress_adaptive",
    "decompress",
    "estimate_entropy",
    "hash_chunk",
    "hash_content",
    "hash_chunk_binary",
    "DeduplicateIndex",
    "HierarchicalHasher",
    "StreamingHasher",
    "get_hash_stats",
    "cosine_similarity",
    "cosine_similarity_batch",
    "cosine_similarity_batch_matrix",
    "top_k_similarities",
    "quantize_embedding",
    "dequantize_embedding",
    "similarity_from_quantized_blob",
    "top_k_from_quantized",
    "count_tokens",
    "generate_diff",
    "truncate_smart",
    "truncate_semantic",
    "compute_delta",
    "apply_delta",
    "diff_stats",
    "DiffDelta",
    "BPETokenizer",
    "get_tokenizer",
    "embed",
    "embed_query",
    "warmup_embeddings",
    "get_model_info",
    # Extreme quantization (binary/ternary)
    "quantize_binary",
    "dequantize_binary",
    "hamming_similarity_binary",
    "batch_hamming_similarity_binary",
    "quantize_ternary",
    "dequantize_ternary",
    "batch_dot_product_ternary",
    "quantize_hybrid",
    "evaluate_quantization_accuracy",
    # Semantic summarization
    "SummarizationConfig",
    "DEFAULT_SUMMARIZATION_CONFIG",
    "Segment",
    "extract_segments",
    "score_segments",
    "summarize_semantic",
    "truncate_with_summarization",
]
